# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'button_label.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bebra(object):
    def setupUi(self, Bebra):
        Bebra.setObjectName("Bebra")
        Bebra.resize(795, 698)
        Bebra.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(Bebra)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 60, 491, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        Bebra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Bebra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menubar.setObjectName("menubar")
        Bebra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Bebra)
        self.statusbar.setObjectName("statusbar")
        Bebra.setStatusBar(self.statusbar)

        self.retranslateUi(Bebra)
        QtCore.QMetaObject.connectSlotsByName(Bebra)

    def retranslateUi(self, Bebra):
        _translate = QtCore.QCoreApplication.translate
        Bebra.setWindowTitle(_translate("Bebra", "MainWindow"))
        self.pushButton.setText(_translate("Bebra", "Нажми на меня"))
        self.label.setToolTip(_translate("Bebra", "<html><head/><body><p><span style=\" font-size:24pt;\">TextLabel</span></p></body></html>"))
        self.label.setText(_translate("Bebra", "TextLabel"))
